version: "3.4"

services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:latest
    restart: "no"
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=root
      - CLICKHOUSE_PASSWORD=root
      - CLICKHOUSE_DB=test
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=0
    ulimits:
      nofile:
        soft: "262144"
        hard: "262144"
    volumes:
      - ../clickhouse/users.xml:/etc/clickhouse-server/users.xml
