services:
  clickhouse-sink-connector-lt:
    extends:
      file: clickhouse-sink-connector-lt-service.yml
      service: clickhouse-sink-connector-lt

  ### MONITORING ####
  prometheus:
    extends:
      file: prometheus-service.yml
      service: prometheus

  grafana:
    extends:
      file: grafana-service.yml
      service: grafana
    volumes:
      - ./config/grafana/config/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./config/grafana/config/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./config/grafana/config/altinity_sink_connector.json:/var/lib/grafana/dashboards/altinity_sink_connector.json
    depends_on:
      - prometheus
    ## END OF MONITORING ###