version: "3.4"

services:
  postgres:
    image: debezium/postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=public
    volumes:
      - ../sql/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
