version: "3.4"

services:
  prometheus:
    container_name: prometheus
    image: bitnami/prometheus:2.36.0
    restart: "no"
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
